const data={
    cars:[
        {
            name:"altroz",
            image:"/images/cars/altroz.jpg",
            payPerDay:30,
            fuelType:"petrol",
            bookedTimeSlots:[],
            capacity:5,
        },
        {
            name:"baleno",
            image:"/images/cars/baleno.jpeg",
            payPerDay:35,
            fuelType:"petrol",
            bookedTimeSlots:[],
            capacity:5,
        },
        {
            name:"dzire",
            image:"/images/cars/dzire.jpeg",
            payPerDay:40,
            fuelType:"disel",
            bookedTimeSlots:[],
            capacity:5,
        },
        {
            name:"etios",
            image:"/images/cars/etios.jpg",
            payPerDay:35,
            fuelType:"disel",
            bookedTimeSlots:[],
            capacity:"5",
        },
        {
            name:"polo",
            image:"/images/cars/polo.jpeg",
            payPerDay:50,
            fuelType:"petrol",
            bookedTimeSlots:[],
            capacity:5,
        },
        {
            name:"verna",
            image:"/images/cars/verna.jpeg",
            payPerDay:80,
            fuelType:"petrol",
            bookedTimeSlots:[],
            capacity:5,
        },
        {
            name:"ritz",
            image:"/images/cars/ritz.jpg",
            payPerDay:30,
            fuelType:"petrol",
            bookedTimeSlots:[],
            capacity:5,
        }
    ]
}
export default data;